
services:

  mongo:
    image: mongo:7.0
    container_name: etl_mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    ulimits:
      nofile:
        soft: 64000
        hard: 64000

  redis:
    image: redis/redis-stack:latest
    container_name: etl_redis
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_ARGS=--port 6379 --bind ${REDIS_BIND} --protected-mode ${REDIS_PROTECTION_MODE}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  celery_worker:
    build: .
    container_name: etl_worker
    restart: unless-stopped
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    networks:
      - backend_network
    user: "1000:1000"

  celery_beat:
    build: .
    container_name: etl_beat
    restart: unless-stopped
    command: celery -A celery_app beat --loglevel=info
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    networks:
      - backend_network

volumes:
  mongo_data:

networks:
  backend_network:
    external: true
